spring.main.banner-mode=off
spring.main.log-startup-info=false
logging.level.root=OFF
keycloak.ssl-verify=true
keycloak.connect-timeout=5s
keycloak.read-timeout=10s
keycloak.availability-check.enabled=true
keycloak.availability-check.timeout=30s
import.validate=true
import.parallel=false
import.cache.enabled=false
import.var-substitution.enabled=false
import.var-substitution.script-evaluation-enabled=false
import.remote-state.enabled=true
import.managed.authentication-flow=no-delete
import.managed.group=no-delete
import.managed.sub-group=no-delete
import.managed.required-action=no-delete
import.managed.client-scope=no-delete
import.managed.scope-mapping=no-delete
import.managed.client-scope-mapping=no-delete
import.managed.component=no-delete
import.managed.sub-component=no-delete
import.managed.identity-provider=no-delete
import.managed.identity-provider-mapper=no-delete
import.managed.role=no-delete
import.managed.client=no-delete
import.managed.client-authorization-resources=no-delete
import.managed.client-authorization-policies=no-delete
import.managed.client-authorization-scopes=no-delete
import.managed.message-bundles=no-delete
import.managed.workflow=no-delete
