---
external_secrets_settings: "{{ (lookup('file', '/workspace/platform/secrets/external-secrets/values.json') | from_json).cloudlab }}"
external_secrets_vault: "{{ external_secrets_settings.vault }}"
external_secrets_store: "{{ external_secrets_settings.store }}"
external_secrets_token: "{{ lookup('env', 'OP_SERVICE_ACCOUNT_TOKEN') }}"
external_secrets_gitops_enabled: "{{ (lookup('file', '/workspace/gitops/roots/public/values.yaml') | from_yaml).externalSecrets.enabled }}"
external_secrets_gitops_reconcile: "{{ (lookup('file', '/workspace/gitops/roots/public/values.yaml') | from_yaml).externalSecrets.reconcile }}"
