apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.cloudlab.store | quote }}
spec:
  conditions:
    - namespaces: {{ concat .Values.cloudlab.consumerNamespaces (.Values.cloudlab.additionalConsumerNamespaces | default list) | uniq | toJson }}
  provider:
    onepasswordSDK:
      vault: {{ .Values.cloudlab.vault | quote }}
      auth:
        serviceAccountSecretRef:
          name: onepassword-token
          namespace: external-secrets
          key: token
