apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: default-replica-count
  namespace: longhorn-system
value: '{"v1":"2","v2":"2"}'
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: default-data-path
  namespace: longhorn-system
value: /var/lib/longhorn
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: default-data-locality
  namespace: longhorn-system
value: best-effort
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: replica-soft-anti-affinity
  namespace: longhorn-system
value: 'false'
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: storage-over-provisioning-percentage
  namespace: longhorn-system
value: '100'
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: storage-minimal-available-percentage
  namespace: longhorn-system
value: '25'
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: storage-reserved-percentage-for-default-disk
  namespace: longhorn-system
value: '30'
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: v1-data-engine
  namespace: longhorn-system
value: 'true'
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: v2-data-engine
  namespace: longhorn-system
value: 'false'
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: upgrade-checker
  namespace: longhorn-system
value: 'false'
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: allow-collecting-longhorn-usage-metrics
  namespace: longhorn-system
value: 'false'
