apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
data:
  cloudlab-private.server: |
    {{ .Values.zone }}:53 {
        errors
        cache 30
        forward . 10.44.0.1 10.44.0.2 {
            max_fails 1
            health_check 2s
        }
    }
  cloudlab-identity.server: |
    login.{{ trimPrefix "internal." .Values.zone }}:53 {
        errors
        cache 30
        forward . 10.44.0.1 10.44.0.2 {
            max_fails 1
            health_check 2s
        }
    }
